# Generated by Django 3.1.5 on 2021-02-14 14:20

import blog_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnails',
            field=models.ImageField(blank=True, upload_to=blog_page.models.upload_to),
        ),
    ]
