# Generated by Django 3.1.5 on 2021-02-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ManyToManyField(related_name='followee', to='user.User', verbose_name='followee')),
                ('follower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user.user', verbose_name='Follower')),
            ],
            options={
                'verbose_name': 'followers',
                'verbose_name_plural': 'followers',
                'db_table': 'followers',
            },
        ),
    ]
